In [1]:
import numpy as np
import pandas as pd

In [57]:
customers = pd.read_csv("data/olist_customers_dataset.csv")
geoloc = pd.read_csv("data/olist_geolocation_dataset.csv")
o_items = pd.read_csv("data/olist_order_items_dataset.csv")
o_payments = pd.read_csv("data/olist_order_payments_dataset.csv")
o_reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")
orders = pd.read_csv("data/olist_orders_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
sellers = pd.read_csv("data/olist_sellers_dataset.csv")
cat_name = pd.read_csv("data/product_category_name_translation.csv")

In [58]:
geo = geoloc.groupby("geolocation_zip_code_prefix", as_index=False).agg({"geolocation_lng":"mean", "geolocation_lat":"mean"})
geo

       geolocation_zip_code_prefix  geolocation_lng  geolocation_lat
0                             1001       -46.634024       -23.550190
1                             1002       -46.634979       -23.548146
2                             1003       -46.635731       -23.548994
3                             1004       -46.634757       -23.549799
4                             1005       -46.636733       -23.549456
...                            ...              ...              ...
19010                        99960       -52.025511       -27.953722
19011                        99965       -52.039850       -28.183372
19012                        99970       -51.874689       -28.343766
19013                        99980       -51.843836       -28.389129
19014                        99990       -51.769362       -28.329595

[19015 rows x 3 columns]

In [ ]:
customers = pd.merge(customers, geo, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="inner")
customers.drop(["customer_zip_code_prefix", "geolocation_zip_code_prefix"], axis=1, inplace=True)

In [60]:
customers.columns = ["customer_id","customer_unique_id","customer_city","customer_state", "customer_lng","customer_lat"]
customers

,customer_id,customer_unique_id,customer_city,customer_state,customer_lng,customer_lat
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,-47.396929,-20.498489
1,5dca924cc99eea2dc5ba40d11ec5dd0f,2761fee7f378f0a8d7682d8a3fa07ab1,franca,SP,-47.396929,-20.498489
2,661897d4968f1b59bfff74c7eb2eb4fc,d06a495406b79cb8203ea21cc0942f8c,franca,SP,-47.396929,-20.498489
3,702b62324327ccba20f1be3465426437,8b3d988f330c1d1c3332ccd440c147b7,franca,SP,-47.396929,-20.498489
4,bdf997bae7ca819b0415f5174d6b4302,866755e25db620f8d7e81b351a15bb2f,franca,SP,-47.396929,-20.498489
...,...,...,...,...,...,...
99158,0b7a30ba373aeb55cf28add5b5477956,8c8173e547e020f411aa55b2fceed861,paicandu,PR,-52.150926,-23.501806
99159,ff6b440b2465bfaef05c675efb48cd15,e38a27b979a552e019e297ecc22dc67b,eugenio de castro,RS,-54.145960,-28.527590
99160,3f7029d9b98a47370cd5f3a97adcbccd,5894d202cc869b4ec460fce3c6ed8cb5,sao paulo,SP,-46.737908,-23.588483
99161,d9110683c7a282144e9fc97660026a28,5cbfdb85ec130898108b32c50d619c39,aparecida de goiania,GO,-49.248175,-16.822735
99162,6fb4f2354f36e554ac80141e9128f528,3cc6f2e1b9199837fabb35ff4bf24884,passo fundo,RS,-52.467505,-28.226596

In [61]:
orders.drop(["order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"], axis=1, inplace=True)
orders = pd.merge(orders, customers, on="customer_id", how="inner")
orders

,order_id,customer_id,order_status,customer_unique_id,customer_city,customer_state,customer_lng,customer_lat
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,-46.587161,-23.576983
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,af07308b275d755c9edb36a90c618231,barreiras,BA,-44.660711,-12.177924
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,-48.514783,-16.745150
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,-35.271143,-5.774190
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,-46.514627,-23.676370
...,...,...,...,...,...,...,...,...
99158,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP,-45.883818,-23.178000
99159,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,da62f9e57a76d978d02ab5362c509660,praia grande,SP,-46.449864,-24.001500
99160,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,-39.373630,-17.898358
99161,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,-42.694574,-22.562825
99162,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,60350aa974b26ff12caad89e55993bd6,lapa,PR,-49.720376,-25.764308

In [62]:
oo = orders.groupby(["customer_id"], as_index=False).agg({"order_id":"count"})
oo["order_id"].value_counts()

1    99163
Name: order_id, dtype: int64

In [63]:
o_items.drop(["order_item_id", "shipping_limit_date"], axis=1, inplace=True)
orders = pd.merge(orders, o_items, on="order_id", how="inner")
orders

,order_id,customer_id,order_status,customer_unique_id,customer_city,customer_state,customer_lng,customer_lat,product_id,seller_id,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,-46.587161,-23.576983,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,af07308b275d755c9edb36a90c618231,barreiras,BA,-44.660711,-12.177924,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,-48.514783,-16.745150,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,-35.271143,-5.774190,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,-46.514627,-23.676370,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...
112343,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,da62f9e57a76d978d02ab5362c509660,praia grande,SP,-46.449864,-24.001500,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10
112344,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,-39.373630,-17.898358,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02
112345,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,-42.694574,-22.562825,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59
112346,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,-42.694574,-22.562825,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59
112347,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,60350aa974b26ff12caad89e55993bd6,lapa,PR,-49.720376,-25.764308,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36

In [64]:
products = products[["product_id", "product_category_name"]]
orders = pd.merge(orders, products, on="product_id", how="inner")
orders

,order_id,customer_id,order_status,customer_unique_id,customer_city,customer_state,customer_lng,customer_lat,product_id,seller_id,price,freight_value,product_category_name
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,-46.587161,-23.576983,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,3a51803cc0d012c3b5dc8b7528cb05f7,sao paulo,SP,-46.534268,-23.564630,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,ef0996a1a279c26e7ecbd737be23d235,sao paulo,SP,-46.655318,-23.600462,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,e781fdcc107d13d865fc7698711cc572,florianopolis,SC,-48.491914,-27.528367,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,14.10,utilidades_domesticas
4,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,af07308b275d755c9edb36a90c618231,barreiras,BA,-44.660711,-12.177924,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumaria
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112343,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,delivered,fb9310710003399b031add3e55f34719,sao paulo,SP,-46.565376,-23.544377,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,356.00,18.12,esporte_lazer
112344,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,delivered,fb9310710003399b031add3e55f34719,sao paulo,SP,-46.565376,-23.544377,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,356.00,18.12,esporte_lazer
112345,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,a49e8e11e850592fe685ae3c64b40eca,campo do tenente,PR,-49.678273,-25.985590,3d2c44374ee42b3003a470f3e937a2ea,ce248b21cb2adc36282ede306b7660e5,55.90,15.14,instrumentos_musicais
112346,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP,-45.883818,-23.178000,ac35486adb7b02598c182c2ff2e05254,e24fc9fcd865784fb25705606fe3dfe7,72.00,13.08,beleza_saude
112347,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,60350aa974b26ff12caad89e55993bd6,lapa,PR,-49.720376,-25.764308,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,beleza_saude

In [ ]:
sellers = pd.merge(sellers, geo, left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="inner")
sellers.drop(["seller_zip_code_prefix", "geolocation_zip_code_prefix"], axis=1, inplace=True)

In [66]:
sellers.columns = ["seller_id","seller_city","seller_state","seller_lng","seller_lat"]
sellers

,seller_id,seller_city,seller_state,seller_lng,seller_lat
0,3442f8959a84dea7ee197c632cb2df15,campinas,SP,-47.061337,-22.893848
1,e0eabded302882513ced4ea3eb0c7059,campinas,SP,-47.061337,-22.893848
2,d1b65fc7debc3361ea86b5f14c68d2e2,mogi guacu,SP,-46.947927,-22.383437
3,ce3ad9de960102d0677a81f5d0bb7b2d,rio de janeiro,RJ,-43.177703,-22.909572
4,1d2732ef8321502ee8488e8bed1ab8cd,rio de janeiro,RJ,-43.177703,-22.909572
...,...,...,...,...,...
3083,f1fdf2d13186575751aa25876536d85c,sao paulo,SP,-46.736453,-23.530647
3084,98dddbc4601dd4443ca174359b237166,sarandi,PR,-51.869960,-23.448041
3085,74871d19219c7d518d0090283e03c137,sao paulo,SP,-46.676925,-23.657851
3086,e603cf3fec55f8697c9059638d6c8eb5,pelotas,RS,-52.323202,-31.751072
3087,9e25199f6ef7e7c347120ff175652c3b,taubate,SP,-45.585652,-23.012009

In [67]:
orders = pd.merge(orders, sellers, on="seller_id", how="inner")
orders

,order_id,customer_id,order_status,customer_unique_id,customer_city,customer_state,customer_lng,customer_lat,product_id,seller_id,price,freight_value,product_category_name,seller_city,seller_state,seller_lng,seller_lat
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,-46.587161,-23.576983,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,maua,SP,-46.444238,-23.680729
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,3a51803cc0d012c3b5dc8b7528cb05f7,sao paulo,SP,-46.534268,-23.564630,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,maua,SP,-46.444238,-23.680729
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,ef0996a1a279c26e7ecbd737be23d235,sao paulo,SP,-46.655318,-23.600462,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,maua,SP,-46.444238,-23.680729
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,e781fdcc107d13d865fc7698711cc572,florianopolis,SC,-48.491914,-27.528367,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,14.10,utilidades_domesticas,maua,SP,-46.444238,-23.680729
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,delivered,02c9e0c05a817d4562ec0e8c90f29dba,itaquaquecetuba,SP,-46.366721,-23.486111,b00a32a0b42fd65efb58a5822009f629,3504c0cb71d7fa48d967e0e4c94d59d9,75.90,7.79,bebes,maua,SP,-46.444238,-23.680729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112091,1ab38815794efa43d269d62b98dae815,a0b67404d84a70ef420a7f99ad6b190a,delivered,2077f7ec37df79c62cc24b7b8f30e8c9,ferraz de vasconcelos,SP,-46.374398,-23.554080,31ec3a565e06de4bdf9d2a511b822b4d,babcc0ab201e4c60188427cae51a5b8b,79.00,14.13,construcao_ferramentas_iluminacao,porto ferreira,SP,-47.478102,-21.866032
112092,b159d0ce7cd881052da94fa165617b05,e0c3bc5ce0836b975d6b2a8ce7bb0e3e,canceled,78a159045124eb7601951b917a42034f,gaspar,SC,-49.004100,-26.904810,241a1ffc9cf969b27de6e72301020268,8501d82f68d23148b6d78bb7c4a42037,19.70,10.96,automotivo,blumenau,SC,-49.102105,-26.888955
112093,735dce2d574afe8eb87e80a3d6229c48,d531d01affc2c55769f6b9ed410d8d3c,delivered,8cf3c6e1d2c8afaab2eda3fa01d4e3d2,fortaleza,CE,-38.560146,-3.741776,1d187e8e7a30417fda31e85679d96f0f,d263fa444c1504a75cbca5cc465f592a,399.00,45.07,moveis_decoracao,americana,SP,-47.312036,-22.743647
112094,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,delivered,e55e436481078787e32349cee9febf5e,teofilo otoni,MG,-41.508224,-17.877228,6e1c2008dea1929b9b6c27fa01381e90,edf3fabebcc20f7463cc9c53da932ea8,219.90,24.12,moveis_decoracao,sao paulo,SP,-46.473162,-23.627052
112095,1565f22aa9452ff278638e87cc895678,56772dfbcbe7df908a284ff0d53adf7d,delivered,6ceea7c1088e15ab3c67980a2d9bb309,sao bernardo do campo,SP,-46.595241,-23.673394,9c1e194db1d35a79d962ea610bfe0868,f3862c2188522d89860c38a3ea8b550d,15.50,12.79,perfumaria,ribeirao preto,SP,-47.767820,-21.177710

In [69]:
orders.drop(["customer_unique_id"], axis=1, inplace=True)
orders

,order_id,customer_id,order_status,customer_city,customer_state,customer_lng,customer_lat,product_id,seller_id,price,freight_value,product_category_name,seller_city,seller_state,seller_lng,seller_lat
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,sao paulo,SP,-46.587161,-23.576983,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,maua,SP,-46.444238,-23.680729
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,sao paulo,SP,-46.534268,-23.564630,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,maua,SP,-46.444238,-23.680729
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,sao paulo,SP,-46.655318,-23.600462,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,maua,SP,-46.444238,-23.680729
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,florianopolis,SC,-48.491914,-27.528367,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,14.10,utilidades_domesticas,maua,SP,-46.444238,-23.680729
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,delivered,itaquaquecetuba,SP,-46.366721,-23.486111,b00a32a0b42fd65efb58a5822009f629,3504c0cb71d7fa48d967e0e4c94d59d9,75.90,7.79,bebes,maua,SP,-46.444238,-23.680729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112091,1ab38815794efa43d269d62b98dae815,a0b67404d84a70ef420a7f99ad6b190a,delivered,ferraz de vasconcelos,SP,-46.374398,-23.554080,31ec3a565e06de4bdf9d2a511b822b4d,babcc0ab201e4c60188427cae51a5b8b,79.00,14.13,construcao_ferramentas_iluminacao,porto ferreira,SP,-47.478102,-21.866032
112092,b159d0ce7cd881052da94fa165617b05,e0c3bc5ce0836b975d6b2a8ce7bb0e3e,canceled,gaspar,SC,-49.004100,-26.904810,241a1ffc9cf969b27de6e72301020268,8501d82f68d23148b6d78bb7c4a42037,19.70,10.96,automotivo,blumenau,SC,-49.102105,-26.888955
112093,735dce2d574afe8eb87e80a3d6229c48,d531d01affc2c55769f6b9ed410d8d3c,delivered,fortaleza,CE,-38.560146,-3.741776,1d187e8e7a30417fda31e85679d96f0f,d263fa444c1504a75cbca5cc465f592a,399.00,45.07,moveis_decoracao,americana,SP,-47.312036,-22.743647
112094,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,delivered,teofilo otoni,MG,-41.508224,-17.877228,6e1c2008dea1929b9b6c27fa01381e90,edf3fabebcc20f7463cc9c53da932ea8,219.90,24.12,moveis_decoracao,sao paulo,SP,-46.473162,-23.627052
112095,1565f22aa9452ff278638e87cc895678,56772dfbcbe7df908a284ff0d53adf7d,delivered,sao bernardo do campo,SP,-46.595241,-23.673394,9c1e194db1d35a79d962ea610bfe0868,f3862c2188522d89860c38a3ea8b550d,15.50,12.79,perfumaria,ribeirao preto,SP,-47.767820,-21.177710

In [70]:
orders.to_csv("clean_ds.csv")